---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:alpine
    commands:
      - apk add --no-cache gcc musl-dev
      - go test -v ./pkg/*
  
services:
  - name: mongo
    image: mongo:4