version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  flakbase:
    build: .
    ports:
      - 9528:9527
    volumes:
      - ./pkg/store/testdata/mongo.json:/data/mongo.json:ro
